[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  VITE_SUPABASE_URL = "https://vrqthuouyxmkgycmmjzt.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycXRodW91eXhta2d5Y21tanp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA2MjEwMTMsImV4cCI6MjA4NjE5NzAxM30.QyYs3TRH6pnHJ6qStkXIA6T29TDpsGl-8Pd1NXkkEtY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
